# Labels: define labels for Issues and Pull Requests
labels:
  - name: A11y
    oldname: good first issue
    color: 77cad8
  - name: API
    oldname: invalid
    color: 04d6c1
  - name: Bug
    color: ee0701
  - name: Component
    oldname: question
    color: cdc2f9
  - name: Deprecated
    oldname: wontfix
    color: ea8aaa
  - name: Documentation
    color: e08953
  - name: Duplicate
    color: cccccc
  - name: Enhancement
    color: 84b6eb
  - name: Extra
    color: dff282
  - name: Future
    color: fc83a5
  - name: Help wanted
    color: ede27d
  - name: Integration testing
    color: fcf53f
  - name: Ok review
    color: 49b21c
  - name: Polymer 2x
    color: 94efab
  - name: Polymer 3x
    color: f998f5
  - name: React
    color: 315691
  - name: Review
    color: 5319e7
  - name: UI
    color: e9b3f9
  - name: Unit tests
    color: ffcccc
  - name: UX
    color: 3ffce9
  - name: Work in progress
    color: fbca04
